[package]
name = "raytracer"
version = "0.1.0"
authors = ["Brandon Smith <mail@brandonsmith.ninja>"]
edition = "2018"

[dependencies]
image = "0.21.2"
crossbeam = "0.7.2"
lazy_static = "1.4.0"

[dependencies.rand]
version = "0.7.2"
features = ["small_rng"]